services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "1"
      MYSQL_USER: jas
      MYSQL_PASSWORD: 123
      MYSQL_DATABASE: traffic
    ports:
      - "3306:3306"
